/* Questões inéditas baseadas nos três materiais da disciplina. Índices de resposta: 0=A, 1=B, 2=C, 3=D. */
const simulados = [
  {titulo:'Fundamentos', nivel:'Fácil', questoes:[
    {id:'1-1',categoria:'Algoritmos',pergunta:'Qual descrição define melhor um algoritmo?',alternativas:['Um conjunto infinito de tentativas até funcionar','Uma sequência finita e ordenada de instruções para resolver um problema','Uma variável que armazena resultados','Um programa escrito obrigatoriamente em C'],correta:1,explicacao:'Um algoritmo descreve passos lógicos, ordenados e finitos para alcançar uma solução. Ele pode ser expresso em linguagem natural ou Portugol antes de ser implementado.'},
    {id:'1-2',categoria:'Variáveis',pergunta:'Durante a execução, o valor de uma variável pode mudar. O que é uma variável?',alternativas:['Uma posição nomeada na memória que guarda um dado','Uma instrução de saída exibida ao usuário','Uma operação aritmética entre números','Uma sequência de instruções sem nome'],correta:0,explicacao:'A variável identifica uma posição de memória. Atribuições posteriores podem substituir o valor ali armazenado.'},
    {id:'1-3',categoria:'Tipos de dados',pergunta:'Para guardar 12, 7,5, "A" e verdadeiro, nessa ordem, quais tipos básicos são adequados?',alternativas:['real, inteiro, lógico, caractere','inteiro, real, caractere, lógico','inteiro, caractere, real, lógico','lógico, real, caractere, inteiro'],correta:1,explicacao:'12 é inteiro; 7,5 possui parte decimal e é real; "A" é caractere; verdadeiro é lógico.'},
    {id:'1-4',categoria:'Entrada e saída',pergunta:'Em um algoritmo que lê a quantidade comprada e exibe o preço total, qual instrução obtém o dado digitado?',alternativas:['escreva(quantidade)','total <- quantidade * preco','leia(quantidade)','fimalgoritmo'],correta:2,explicacao:'leia recebe a entrada. A atribuição com multiplicação processa os dados, e escreva produz saída.'},
    {id:'1-5',categoria:'Processamento',pergunta:'Uma loja lê preço e quantidade para calcular o total. Qual é a etapa de processamento?',alternativas:['leia(preco)','leia(quantidade)','escreva(total)','total <- preco * quantidade'],correta:3,explicacao:'O processamento transforma entradas em um resultado: multiplica o preço pela quantidade e atribui o produto a total.'},
    {id:'1-6',categoria:'Aritmética',pergunta:'Se unidades = 6 e preco = 15, qual valor recebe total após total <- unidades * preco?',alternativas:['21','90','9','60'],correta:1,explicacao:'Substitua os valores: total <- 6 * 15. Logo, total recebe 90.'},
    {id:'1-7',categoria:'Sequência',pergunta:'Analise as instruções executadas nesta ordem. O que aparece na tela?',codigo:'algoritmo "Sequencia"\nvar\n    valor : inteiro\ninicio\n    valor <- 4\n    valor <- valor + 3\n    escreva(valor)\nfimalgoritmo',alternativas:['3','4','7','43'],correta:2,explicacao:'Primeiro valor recebe 4. Depois recebe o valor anterior mais 3: 4 + 3 = 7. escreva exibe 7.'},
    {id:'1-8',categoria:'Portugol',pergunta:'Um algoritmo deve ler a nota de duas avaliações e calcular a média aritmética. Qual atribuição está correta?',alternativas:['media <- nota1 + nota2 / 2','media <- (nota1 + nota2) / 2','media <- nota1 * nota2 / 2','media <- 2 / (nota1 + nota2)'],correta:1,explicacao:'Some as duas notas primeiro, usando parênteses, e divida o total por 2. Sem parênteses, apenas a segunda nota seria dividida.'},
    {id:'1-9',categoria:'Relacionais',pergunta:'Se idade = 18, qual resultado da comparação idade >= 18?',alternativas:['verdadeiro','falso','18','0'],correta:0,explicacao:'O operador >= significa maior ou igual. Como 18 é igual a 18, a comparação resulta em verdadeiro.'},
    {id:'1-10',categoria:'Entrada → processamento → saída',pergunta:'Para mostrar o valor de um produto após desconto, qual ordem segue uma estrutura sequencial?',alternativas:['Exibir o desconto, ler o preço, calcular o total','Calcular o total, ler o preço, exibir o valor','Ler o preço, calcular o valor com desconto, exibir o resultado','Ler o preço, exibir o resultado, calcular o desconto'],correta:2,explicacao:'Primeiro obtenha a entrada; depois calcule o desconto e o valor final; por último mostre a saída solicitada.'}
  ]},
  {titulo:'Expressões e Operadores',nivel:'Fácil / Médio',questoes:[
    {id:'2-1',categoria:'Precedência',pergunta:'Qual é o resultado de 6 + 3 * 4?',alternativas:['36','18','24','15'],correta:1,explicacao:'1. Multiplicação antes da soma: 3 * 4 = 12.\n2. 6 + 12 = 18.'},
    {id:'2-2',categoria:'MOD',pergunta:'Qual é o resultado de 29 mod 6?',alternativas:['4','5','6','3'],correta:1,explicacao:'6 cabe 4 vezes em 29: 4 * 6 = 24. O resto é 29 - 24 = 5. MOD devolve o resto.'},
    {id:'2-3',categoria:'DIV',pergunta:'Qual é o resultado da divisão inteira 29 div 6?',alternativas:['4','5','4,83','6'],correta:0,explicacao:'29 = 6 * 4 + 5. DIV retorna apenas o quociente inteiro 4; MOD retornaria 5.'},
    {id:'2-4',categoria:'Potência e raiz',pergunta:'Qual é o resultado de raiz(potencia(3, 4))?',alternativas:['6','9','12','81'],correta:1,explicacao:'1. potencia(3, 4) = 3⁴ = 81.\n2. raiz(81) = 9.'},
    {id:'2-5',categoria:'Operadores lógicos',pergunta:'Se A = verdadeiro e B = falso, qual é o resultado de não(A e B)?',alternativas:['falso','verdadeiro','A','B'],correta:1,explicacao:'1. A e B = verdadeiro e falso = falso.\n2. não(falso) = verdadeiro.'},
    {id:'2-6',categoria:'Expressões booleanas',pergunta:'X = 8, Y = 3, L = falso. Qual é o resultado de (X - Y > 4) e (L ou Y == 3)?',alternativas:['falso','verdadeiro','5','3'],correta:1,explicacao:'1. 8 - 3 = 5; 5 > 4 é verdadeiro.\n2. 3 == 3 é verdadeiro; falso ou verdadeiro é verdadeiro.\n3. Verdadeiro e verdadeiro = verdadeiro.'},
    {id:'2-7',categoria:'Precedência lógica',pergunta:'Sem parênteses, quanto vale verdadeiro ou falso e falso?',alternativas:['falso','verdadeiro','0','Indefinido'],correta:1,explicacao:'O operador e tem precedência sobre ou. Primeiro falso e falso = falso; depois verdadeiro ou falso = verdadeiro.'},
    {id:'2-8',categoria:'Operadores relacionais',pergunta:'Se P = 7 e Q = 7, qual expressão resulta em falso?',alternativas:['P == Q','P <= Q','P != Q','P >= Q'],correta:2,explicacao:'P e Q são iguais a 7. Portanto P != Q (diferentes) é falso; as outras três comparações são verdadeiras.'},
    {id:'2-9',categoria:'Aritmética e comparação',pergunta:'Qual o resultado de (17 mod 5 + 2) == (11 div 3 + 1)?',alternativas:['verdadeiro','falso','4','5'],correta:0,explicacao:'1. 17 mod 5 = 2, então o lado esquerdo é 2 + 2 = 4.\n2. 11 div 3 = 3, então o lado direito é 3 + 1 = 4.\n3. 4 == 4 é verdadeiro.'},
    {id:'2-10',categoria:'Negação e precedência',pergunta:'A = 2, B = 5. Qual resultado de não(A > B) e (potencia(A, 2) < B)?',alternativas:['falso','verdadeiro','2','5'],correta:1,explicacao:'1. 2 > 5 é falso; não(falso) é verdadeiro.\n2. potencia(2, 2) = 4 e 4 < 5 é verdadeiro.\n3. Verdadeiro e verdadeiro = verdadeiro.'}
  ]},
  {titulo:'Portugol e Teste de Mesa',nivel:'Médio',questoes:[
    {id:'3-1',categoria:'Porcentagem',pergunta:'Um algoritmo lê preco = 240 e aplica desconto de 15%. Qual valor final deve exibir?',alternativas:['204','225','36','276'],correta:0,explicacao:'1. Desconto: 240 * 15 / 100 = 36.\n2. Valor final: 240 - 36 = 204.'},
    {id:'3-2',categoria:'Teste de mesa',pergunta:'Após executar o algoritmo, qual número é exibido?',codigo:'algoritmo "Atualiza"\nvar\n    a, b : inteiro\ninicio\n    a <- 3\n    b <- a + 4\n    a <- b * 2\n    escreva(a - b)\nfimalgoritmo',alternativas:['3','7','14','21'],correta:1,explicacao:'1. a = 3.\n2. b = 3 + 4 = 7.\n3. a = 7 * 2 = 14.\n4. escreva(a - b) exibe 14 - 7 = 7.'},
    {id:'3-3',categoria:'Saída de dados',pergunta:'No algoritmo abaixo, qual informação pedida no enunciado NÃO aparece na saída? O enunciado exige mostrar desconto e preço final.',codigo:'algoritmo "Compra"\nvar\n    preco, desconto, final : real\ninicio\n    leia(preco)\n    desconto <- preco * 0.08\n    final <- preco - desconto\n    escreva(final)\nfimalgoritmo',alternativas:['Preço final','Valor do desconto','Preço de entrada','O valor de final é calculado'],correta:1,explicacao:'O algoritmo calcula desconto e final, mas escreva(final) mostra apenas o preço final. Falta escreva(desconto) para atender ao enunciado.'},
    {id:'3-4',categoria:'Conversão',pergunta:'Um algoritmo lê tempo em horas e precisa mostrar minutos. Qual processamento correto?',alternativas:['minutos <- horas / 60','minutos <- horas + 60','minutos <- horas * 60','minutos <- 60 - horas'],correta:2,explicacao:'Cada hora tem 60 minutos. Multiplique o número de horas por 60 antes de exibir minutos.'},
    {id:'3-5',categoria:'Teste de mesa',pergunta:'Com distancia = 180 e tempo = 3, o que será exibido?',codigo:'algoritmo "Viagem"\nvar\n    distancia, tempo, velocidade : real\ninicio\n    leia(distancia)\n    leia(tempo)\n    velocidade <- distancia / tempo\n    escreva("Velocidade: ", velocidade)\nfimalgoritmo',alternativas:['Velocidade: 540','Velocidade: 60','Velocidade: 183','Velocidade: 3'],correta:1,explicacao:'1. distancia = 180 e tempo = 3.\n2. velocidade = 180 / 3 = 60.\n3. A saída combina o texto com o valor: Velocidade: 60.'},
    {id:'3-6',categoria:'Salários',pergunta:'Uma pessoa recebe 3.750 e o salário usado como referência é 1.500. Quantos salários de referência recebe?',alternativas:['1,5','2','2,5','5,25'],correta:2,explicacao:'Divida o salário da pessoa pelo valor de referência: 3750 / 1500 = 2,5.'},
    {id:'3-7',categoria:'Teste de mesa',pergunta:'Qual é o valor final de x?',codigo:'algoritmo "TrocaValores"\nvar\n    x, y : inteiro\ninicio\n    x <- 10\n    y <- x\n    x <- x + 5\n    y <- y + 2\nfimalgoritmo',alternativas:['10','12','15','17'],correta:2,explicacao:'1. x = 10.\n2. y copia 10.\n3. x = 10 + 5 = 15.\n4. y muda para 12, mas isso não altera x. Valor final de x: 15.'},
    {id:'3-8',categoria:'Portugol',pergunta:'Um algoritmo lê preco = 80 e aplica acréscimo de 25%. Qual instrução calcula o novo preço?',alternativas:['novo <- preco * 0.25','novo <- preco + preco * 0.25','novo <- preco / 0.25','novo <- preco - preco * 0.25'],correta:1,explicacao:'O acréscimo é 80 * 0,25 = 20. O novo preço é 80 + 20 = 100; por isso é preciso somar o acréscimo ao valor original.'},
    {id:'3-9',categoria:'Média',pergunta:'Com notas 6, 8 e 10, qual saída do algoritmo?',codigo:'algoritmo "Notas"\nvar\n    n1, n2, n3, media : real\ninicio\n    leia(n1, n2, n3)\n    media <- (n1 + n2 + n3) / 3\n    escreva(media)\nfimalgoritmo',alternativas:['6','7','8','24'],correta:2,explicacao:'Some as notas: 6 + 8 + 10 = 24. Divida por 3: media = 8. escreva(media) exibe 8.'},
    {id:'3-10',categoria:'Entrada → processamento → saída',pergunta:'Para calcular o valor a pagar por 4 ingressos de R$ 18 cada, qual par identifica corretamente entrada e saída?',alternativas:['Entrada: total; saída: quantidade e preço','Entrada: quantidade e preço; saída: total','Entrada: multiplicação; saída: quantidade','Entrada: escreva; saída: leia'],correta:1,explicacao:'Quantidade e preço são dados de entrada. O processamento faz 4 * 18 = 72. O valor total, R$ 72, é a saída.'}
  ]},
  {titulo:'Simulação da Prova',nivel:'Médio / Difícil',questoes:[
    {id:'4-1',categoria:'Conceitos',pergunta:'Um colega afirma que uma variável não pode receber outro valor depois de criada. Qual resposta está correta?',alternativas:['Correto; o valor permanece fixo até o fim','Incorreto; uma variável nomeia memória e seu conteúdo pode mudar durante a execução','Correto; apenas caracteres podem mudar','Incorreto; variáveis são comandos de saída'],correta:1,explicacao:'Variáveis armazenam dados em posições nomeadas de memória; atribuições posteriores substituem o conteúdo, como x <- x + 1.'},
    {id:'4-2',categoria:'Expressão lógica',pergunta:'Considere X = 4, Y = 6, Z = 9 e L = verdadeiro. Qual é o valor de não((X * Y > Z * 2) e L) ou (Y mod X == 2)?',alternativas:['falso','verdadeiro','2','24'],correta:1,explicacao:'1. 4 * 6 = 24 e 9 * 2 = 18; 24 > 18 é verdadeiro.\n2. Verdadeiro e L = verdadeiro; não(verdadeiro) = falso.\n3. 6 mod 4 = 2; 2 == 2 é verdadeiro.\n4. Falso ou verdadeiro = verdadeiro.'},
    {id:'4-3',categoria:'Porcentagem em Portugol',pergunta:'Um serviço custa R$ 160 e recebe taxa de 12%. Qual algoritmo calcula e mostra tanto a taxa quanto o total?',alternativas:['taxa <- 160 * 0.12; total <- 160 + taxa; escreva(taxa, total)','taxa <- 160 * 12; total <- 160 + taxa; escreva(total)','taxa <- 160 * 0.12; total <- 160 - taxa; escreva(taxa, total)','total <- 160 * 0.12; escreva(total)'],correta:0,explicacao:'1. Taxa = 160 * 0,12 = 19,20.\n2. Total = 160 + 19,20 = 179,20.\n3. É preciso exibir ambos os valores solicitados.'},
    {id:'4-4',categoria:'Teste de mesa',pergunta:'Com capital = 800 e taxa = 7, qual texto e valor são exibidos?',codigo:'algoritmo "Rendimento"\nvar\n    capital, taxa, ganho, saldo : real\ninicio\n    leia(capital, taxa)\n    ganho <- capital * (taxa / 100)\n    saldo <- capital + ganho\n    escreva("Ganho: ", ganho)\n    escreva("Saldo: ", saldo)\nfimalgoritmo',alternativas:['Ganho: 56; Saldo: 856','Ganho: 7; Saldo: 807','Ganho: 56; Saldo: 800','Ganho: 5600; Saldo: 6400'],correta:0,explicacao:'1. taxa / 100 = 7 / 100 = 0,07.\n2. ganho = 800 * 0,07 = 56.\n3. saldo = 800 + 56 = 856.\n4. As duas linhas mostram Ganho: 56 e Saldo: 856.'},
    {id:'4-5',categoria:'Expressão lógica',pergunta:'A = 3, B = 8, C = 2. Qual resultado de (B div A + C) >= 4 e não(A + C == B)?',alternativas:['falso','verdadeiro','4','5'],correta:1,explicacao:'1. 8 div 3 = 2; 2 + 2 = 4; 4 >= 4 é verdadeiro.\n2. 3 + 2 = 5; 5 == 8 é falso; não(falso) é verdadeiro.\n3. Verdadeiro e verdadeiro = verdadeiro.'},
    {id:'4-6',categoria:'Precedência',pergunta:'M = 5, N = 2. Quanto vale não(M < N) e (raiz(potencia(N, 4)) == 4) ou falso?',alternativas:['falso','verdadeiro','4','16'],correta:1,explicacao:'1. 5 < 2 é falso; não(falso) é verdadeiro.\n2. potencia(2,4) = 16; raiz(16) = 4; 4 == 4 é verdadeiro.\n3. Verdadeiro e verdadeiro = verdadeiro; verdadeiro ou falso = verdadeiro.'},
    {id:'4-7',categoria:'Portugol e saída',pergunta:'Um algoritmo lê 12 caixas, cada uma com 24 unidades, e imprime apenas o total de unidades. Qual par processamento/saída atende ao pedido?',alternativas:['total <- 12 + 24; escreva(total)','total <- 12 * 24; escreva(12)','total <- 12 * 24; escreva(total)','total <- 24 / 12; escreva(total)'],correta:2,explicacao:'A quantidade total é 12 * 24 = 288. O comando escreva(total) mostra o resultado calculado, não um dos dados de entrada.'},
    {id:'4-8',categoria:'Teste de mesa',pergunta:'Se horas = 2, valor_hora = 35 e adicional = 10, qual valor sai na tela?',codigo:'algoritmo "Pagamento"\nvar\n    horas, valor_hora, adicional, base, total : real\ninicio\n    leia(horas, valor_hora, adicional)\n    base <- horas * valor_hora\n    total <- base + base * (adicional / 100)\n    escreva(total)\nfimalgoritmo',alternativas:['72','77','80','700'],correta:1,explicacao:'1. base = 2 * 35 = 70.\n2. adicional = 70 * (10 / 100) = 7.\n3. total = 70 + 7 = 77. escreva(total) exibe 77.'},
    {id:'4-9',categoria:'Aritmética e lógica',pergunta:'Qual resultado de (25 mod 4 * 3) > (17 div 5 + 5) ou não(falso)?',alternativas:['falso','verdadeiro','3','9'],correta:1,explicacao:'1. 25 mod 4 = 1; 1 * 3 = 3.\n2. 17 div 5 = 3; 3 + 5 = 8; 3 > 8 é falso.\n3. não(falso) é verdadeiro.\n4. Falso ou verdadeiro = verdadeiro.'},
    {id:'4-10',categoria:'Análise de algoritmo',pergunta:'Uma papelaria lê o preço unitário e a quantidade, calcula subtotal e oferece desconto de 5% no subtotal. Quais valores precisa exibir para atender ao pedido "informe desconto e valor a pagar"?',alternativas:['Apenas preço unitário e quantidade','Subtotal e preço unitário','Desconto calculado e subtotal menos desconto','Apenas a porcentagem 5%'],correta:2,explicacao:'1. subtotal = preço unitário * quantidade.\n2. desconto = subtotal * 0,05.\n3. valor a pagar = subtotal - desconto.\n4. O pedido exige exibir o desconto em dinheiro e o valor a pagar.'}
  ]}
];
