'use strict';
const app = document.querySelector('#app');
const key = 'simulado-algoritmos-melhores-v1';
const letters = ['A','B','C','D'];
let state = null;
let studyLast = null;
const shuffle = array => {const result=[...array];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result};
const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bestScores(){try {const value=JSON.parse(localStorage.getItem(key)||'{}');return value && typeof value==='object' ? value : {}}catch{return {}}}
function saveBest(index,score){try{const best=bestScores();best[index]=Math.max(Number(best[index])||0,score);localStorage.setItem(key,JSON.stringify(best))}catch{/* armazenamento indisponível */}}
function focusPage(){app.focus({preventScroll:true});window.scrollTo(0,0)}
function renderHome(){state=null;const best=bestScores();app.innerHTML=`<div class="home-intro"><div class="eyebrow">// PREPARAÇÃO PARA A PROVA</div><h1>Simulado de<br>Algoritmos<span class="brand-dot">.</span></h1><p>Pratique lógica, operadores, Portugol e teste de mesa antes da prova. Responda, confira o raciocínio e revise seus erros.</p></div><div class="section-head"><h2>Escolha um simulado</h2><small>04 simulados · 10 questões cada</small></div><div class="cards">${simulados.map((item,i)=>`<button type="button" class="card" data-start="${i}"><span class="card-top"><span class="card-no">SIMULADO 0${i+1}</span><span class="arrow" aria-hidden="true">↗</span></span><span><h3>${escapeHtml(item.titulo)}</h3><p>${Number.isInteger(best[i])?`Melhor resultado: ${best[i]}/10`:'Ainda não realizado.'}</p></span></button>`).join('')}</div><div class="section-label">// OUTRAS FORMAS DE ESTUDAR</div><div class="secondary-grid"><button type="button" class="card" data-action="study"><span class="card-top"><span class="card-no">PRÁTICA CONTÍNUA</span><span class="arrow" aria-hidden="true">↗</span></span><span><h3>Modo estudo</h3><p>Questões aleatórias e correção na hora.</p></span></button><button type="button" class="card" data-action="revision"><span class="card-top"><span class="card-no">CONSULTA RÁPIDA</span><span class="arrow" aria-hidden="true">↗</span></span><span><h3>Revisão rápida</h3><p>Os conceitos principais em poucos minutos.</p></span></button></div>`;focusPage()}
function createRound(index,redo=false){const base=simulados[index].questoes;state={mode:'simulado',index,redo,questions:redo?shuffle(base):[...base],position:0,answers:[],selected:null,confirmed:false,options:null};renderQuestion()}
function nextStudy(){const pool=simulados.flatMap(s=>s.questoes);const available=pool.filter(q=>q.id!==studyLast);const q=available[Math.floor(Math.random()*available.length)];studyLast=q.id;state={mode:'estudo',questions:[q],position:0,answers:[],selected:null,confirmed:false,options:null};renderQuestion()}
function questionOptions(){if(!state.options){const q=state.questions[state.position];state.options=state.mode==='simulado'&&state.redo?shuffle(q.alternativas.map((text,index)=>({text,index}))):q.alternativas.map((text,index)=>({text,index}))}return state.options}
function renderQuestion(){const q=state.questions[state.position];const total=state.questions.length;const study=state.mode==='estudo';const options=questionOptions();const selected=state.selected;const confirmed=state.confirmed;const answer=options.findIndex(o=>o.index===q.correta);app.innerHTML=`<div class="quiz-layout"><div class="topline"><button class="back" data-action="home" type="button">← Voltar ao início</button><span>${study?'MODO ESTUDO':`SIMULADO 0${state.index+1}`}</span></div><div class="progress" role="progressbar" aria-label="Progresso do simulado" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${study?0:state.position+1}"><span style="width:${study?100:(state.position+1)/total*100}%"></span></div><h1 class="quiz-title">${study?'Modo estudo':`Simulado ${state.index+1}`}</h1><p class="quiz-sub">${study?'Pratique sem limite de questões.':`Questão ${state.position+1} de ${total} · ${escapeHtml(simulados[state.index].titulo)}`}</p><section class="question-panel" aria-labelledby="question-title"><div class="tag">${escapeHtml(q.categoria).toUpperCase()}</div><h2 id="question-title" class="question">${escapeHtml(q.pergunta)}</h2>${q.codigo?`<div class="code-wrap"><pre><code>${escapeHtml(q.codigo)}</code></pre></div>`:''}<fieldset class="choices"><legend class="sr-only">Selecione uma alternativa</legend>${options.map((option,i)=>`<label class="choice ${confirmed?(option.index===q.correta?'correct':i===selected?'incorrect':''):''}"><input type="radio" name="answer" value="${i}" ${selected===i?'checked':''} ${confirmed?'disabled':''}><span class="choice-letter">${letters[i]}</span><span>${escapeHtml(option.text)}</span></label>`).join('')}</fieldset>${confirmed?`<div class="feedback ${options[selected].index===q.correta?'correct':'incorrect'}" role="status"><strong>${options[selected].index===q.correta?'✓ Resposta correta!':'✕ Resposta incorreta.'}</strong><p>Resposta correta: ${letters[answer]} — ${escapeHtml(options[answer].text)}</p><p class="explain">${escapeHtml(q.explicacao)}</p></div>`:''}<div class="action-row">${confirmed?`<button class="btn" type="button" data-action="next">${study?'Próxima questão':state.position===total-1?'Ver resultado':'Próxima questão'} →</button>`:`<button class="btn" type="button" data-action="confirm" ${selected===null?'disabled':''}>Confirmar resposta</button>`}</div></section></div>`;focusPage()}
function confirmAnswer(){if(!state||state.selected===null||state.confirmed)return;state.confirmed=true;const q=state.questions[state.position];state.answers.push({q,selected:state.options[state.selected],options:state.options});renderQuestion();document.querySelector('.feedback')?.scrollIntoView({block:'nearest',behavior:'smooth'})}
function nextQuestion(){if(!state||!state.confirmed)return;if(state.mode==='estudo')return nextStudy();if(state.position===state.questions.length-1)return renderResult();state.position++;state.selected=null;state.confirmed=false;state.options=null;renderQuestion()}
function renderResult(){const score=state.answers.filter(a=>a.selected.index===a.q.correta).length;saveBest(state.index,score);const message=score<=4?'Você ainda precisa revisar alguns conteúdos.':score<=6?'Você está evoluindo, mas vale revisar os pontos que errou.':score<=8?'Bom resultado. Revise os erros antes da prova.':score===9?'Ótimo resultado. Você está bem preparado.':'Excelente! Você acertou todas as questões.';app.innerHTML=`<div class="result-layout"><div class="eyebrow">// SIMULADO 0${state.index+1} · ${escapeHtml(simulados[state.index].titulo).toUpperCase()}</div><h1>Simulado concluído<span class="brand-dot">.</span></h1><div class="score-big">${score}<span> / 10</span></div><div class="stats"><div class="stat">Aproveitamento: <strong>${score*10}%</strong></div><div class="stat">Erros: <strong>${10-score}</strong></div></div><p style="margin-top:25px">${message}</p><div class="action-row"><button class="btn" type="button" data-action="errors" ${score===10?'disabled':''}>Revisar erros</button><button class="btn btn-outline" type="button" data-action="redo">Refazer simulado</button><button class="btn btn-outline" type="button" data-action="copy">Copiar resultado</button><button class="btn btn-quiet" type="button" data-action="home">Voltar ao início</button></div><p id="copy-status" role="status" aria-live="polite"></p></div>`;focusPage()}
function renderErrors(){const wrong=state.answers.filter(a=>a.selected.index!==a.q.correta);app.innerHTML=`<div class="result-layout"><button type="button" class="back" data-action="result">← Voltar ao resultado</button><div class="eyebrow">// SIMULADO 0${state.index+1}</div><h1>Revisão dos erros<span class="brand-dot">.</span></h1><p>${wrong.length} ${wrong.length===1?'questão para revisar':'questões para revisar'}.</p>${wrong.map(({q,selected,options},i)=>`<article class="review-card"><div class="tag">${String(i+1).padStart(2,'0')} / ${escapeHtml(q.categoria).toUpperCase()}</div><h2 class="question">${escapeHtml(q.pergunta)}</h2>${q.codigo?`<div class="code-wrap"><pre><code>${escapeHtml(q.codigo)}</code></pre></div>`:''}<p>Sua resposta: <strong>${letters[options.indexOf(selected)]} — ${escapeHtml(selected.text)}</strong></p><p>Correta: <strong>${letters[options.findIndex(o=>o.index===q.correta)]} — ${escapeHtml(q.alternativas[q.correta])}</strong></p><p class="explain">${escapeHtml(q.explicacao)}</p></article>`).join('')}</div>`;focusPage()}
const topics=[['Algoritmos','Passos finitos, ordenados e lógicos que resolvem um problema.'],['Variáveis','Posições nomeadas na memória. O valor pode mudar durante a execução.'],['Tipos de dados','Inteiro: sem parte decimal; real: com parte decimal; caractere: texto; lógico: verdadeiro ou falso.'],['Operadores aritméticos','Use +, −, *, /; potência e raiz aparecem nas expressões da disciplina.'],['Operadores relacionais','>, <, >=, <=, == e != comparam valores e produzem verdadeiro ou falso.'],['Operadores lógicos','não inverte; e exige ambos verdadeiros; ou exige pelo menos um verdadeiro. Ordem: não, e, ou.'],['Precedência','Parênteses internos → potência e raiz → multiplicação, divisão, mod e div → soma e subtração → relações → lógica.'],['MOD','Resto da divisão inteira: 17 mod 5 = 2.'],['DIV','Quociente inteiro da divisão: 17 div 5 = 3.'],['Entrada → processamento → saída','leia obtém dados; atribuições calculam; escreva exibe o que o enunciado pediu.'],['Teste de mesa','Acompanhe as variáveis linha por linha e anote exatamente as saídas do escreva.'],['Portugol','Declare variáveis, leia entradas, faça as atribuições com <- e escreva todas as saídas solicitadas.']];
function renderRevision(){app.innerHTML=`<div class="revision-layout"><button class="back" type="button" data-action="home">← Voltar ao início</button><div class="eyebrow">// CONSULTA RÁPIDA</div><h1>Revisão rápida<span class="brand-dot">.</span></h1><p>Conceitos dos materiais da disciplina para consultar antes de praticar.</p><div class="revision-grid">${topics.map(([name,description])=>`<article class="review-card"><h2 class="question">${escapeHtml(name)}</h2><p>${escapeHtml(description)}</p></article>`).join('')}</div><div class="action-row"><button class="btn" type="button" data-action="study">Praticar no modo estudo →</button></div></div>`;focusPage()}
async function copyResult(){const score=state.answers.filter(a=>a.selected.index===a.q.correta).length;const message=`📚 Simulado de Algoritmos\nSimulado ${state.index+1} — ${simulados[state.index].titulo}\nResultado: ${score}/10\nAproveitamento: ${score*10}%\nPreparando para a prova de Algoritmos.`;const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText(message);status.textContent='Resultado copiado.'}catch{status.textContent='Não foi possível copiar automaticamente neste navegador.'}}
app.addEventListener('change',event=>{if(event.target.matches('input[name="answer"]')&&state&&!state.confirmed){state.selected=Number(event.target.value);document.querySelector('[data-action="confirm"]').disabled=false}});
app.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.start!==undefined)return createRound(Number(button.dataset.start));switch(button.dataset.action){case'home':renderHome();break;case'study':nextStudy();break;case'revision':renderRevision();break;case'confirm':confirmAnswer();break;case'next':nextQuestion();break;case'result':renderResult();break;case'errors':renderErrors();break;case'redo':createRound(state.index,true);break;case'copy':copyResult();break}});
document.querySelector('#brand').addEventListener('click',renderHome);
renderHome();
